{% assign githubLink = "https://github.com/ARgorithm" %}
{% assign serverlink = "https://argorithm.github.io/Server" %}
{% assign docslink = "https://argorithm.github.io/toolkit" %}
{% assign downloadapp = "https://github.com/ARgorithm/Unity-App/releases" %}
{% assign pypipage = "https://pypi.org/project/ARgorithmToolkit/" %}
{% assign dockerimage = "https://hub.docker.com/r/alanjohn/argorithm-server" %}